proxy:
  # isEnabled turns on proxy check
  isEnabled: true
  # without isExternal server will use proxy data downside
  isExternal: false
  url: "http://193.8.56.119:9183"
  # use isAuth if proxy needs authentication
  isAuth: false
  username: "nmvrpple-DE-rotate"
  password: "9cf8udu7x26b"