token : 1416982745:AAGCiyC1EGOpD8GEqVPhbCLL_ptwRP4fvWU
mongo_db : "instagram"
mongo_collection : "accounts"
auth_socket_port : "5012"
auth_socket_host : "localhost"
stat_socket_port : "5013"
stat_socket_host : "localhost"
info_socket_port : "5014"
info_socket_host : "localhost"
